language: python
python:
  - "2.6"
  - "2.7"


# command to install dependencies
install:
  - "pip install -r requirements/compiled.txt --use-mirrors"

before_script:
  - "mysql -e 'create database bisect;'"
  - "git submodule update --init --recursive"
  - "mv bisectcloud/settings/local.py-dist bisectcloud/settings/local.py"

script: "./manage.py test"
