language: python
python:
  - "2.6"
  - "2.7"

env:
  - DISPLAY=':99.0' DB=mongo DB=redis

# command to install dependencies
install:
  - "git submodule update --init --recursive"
  - "pip install -r requirements/dev.txt --use-mirrors"

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "mysql -e 'create database bisectcloud;'"
  - "mv bisectcloud/settings/local.py-dist bisectcloud/settings/local.py"
  - "./manage.py syncdb --noinput"

script: "./manage.py test"
